# Generated by Django 4.1.3 on 2022-11-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinearGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sp', models.PositiveIntegerField(default=0)),
                ('number_st', models.PositiveIntegerField(default=0)),
                ('day', models.DateField()),
            ],
            options={
                'verbose_name': 'Kunlik Statistika',
                'verbose_name_plural': 'Kunlar Statistikasi',
            },
        ),
        migrations.CreateModel(
            name='MainDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_asked', models.PositiveIntegerField(default=0)),
                ('money_sent', models.PositiveIntegerField(default=0)),
                ('money_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Asosiy Malumotlar',
                'verbose_name_plural': 'Asosiy Malumotlar',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_phisical_person', models.BooleanField(choices=[(0, 'Yuridik'), (1, 'Jismoniy')], verbose_name='Shaxs turi')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('phone', models.CharField(max_length=9, verbose_name='telefon raqam')),
                ('name_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma nomi')),
                ('condition', models.IntegerField(choices=[(1, 'Yangi'), (2, 'Tasdiqlangan'), (3, 'Moderatsiyada'), (4, 'Bekor qilingan')], default=1, verbose_name='Holat')),
                ('budget', models.PositiveIntegerField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('is_counted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Homiy',
                'verbose_name_plural': 'Homiylar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('phone', models.CharField(max_length=9, verbose_name='telefon raqam')),
                ('student_type', models.IntegerField(choices=[(1, 'Bakalavr'), (2, 'Magistratura'), (3, 'Aspirantura')], verbose_name='Talim turi')),
                ('request', models.PositiveIntegerField(verbose_name='Soralgan pul miqdori')),
                ('send', models.PositiveIntegerField(default=0, verbose_name='Tolangan pul miqdori')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Universitetning Nomi')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universitet',
            },
        ),
        migrations.CreateModel(
            name='StudentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('money', models.PositiveIntegerField(verbose_name='Pull miqdori')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sponsor', verbose_name='Homiy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Talaba va Homiy',
                'verbose_name_plural': 'Talabalar va Homiylar',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.university', verbose_name='Institut'),
        ),
    ]
