# Generated by Django 4.1.3 on 2022-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sponsor_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='send',
            field=models.PositiveIntegerField(default=0, verbose_name='Tolangan pul miqdori'),
        ),
    ]
