# Generated by Django 4.1.3 on 2022-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='person',
            field=models.IntegerField(choices=[(1, 'Yuridik'), (2, 'Jismoniy')], verbose_name='shaxs turi'),
        ),
    ]
