# Generated by Django 4.1.3 on 2022-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_sponsormodel_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Tasdiqlanmagan'), (3, 'Moderatsiyada'), (4, 'Bekor qilingan')], verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='student_type',
            field=models.IntegerField(choices=[(1, 'Bakalavr'), (2, 'Magistratura'), (3, 'Aspirantura')], verbose_name='Talim turi'),
        ),
    ]
