# Generated by Django 4.1.3 on 2022-11-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_sponsormodel_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
