# Generated by Django 4.1.3 on 2022-11-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_sponsormodel_budget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='UniversityModel',
        ),
    ]
