# Generated by Django 4.1.3 on 2022-11-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_university_universitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Tasdiqlanmagan'), (3, 'Moderatsiyada'), (4, 'Bekor qilingan')], default=1, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='person',
            field=models.BooleanField(choices=[(0, 'Yuridik'), (1, 'Jismoniy')], verbose_name='shaxs turi'),
        ),
    ]
