# Generated by Django 4.1.3 on 2022-11-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_sponsormodel_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Tasdiqlanmagan'), (3, 'Moderatsiyada'), (4, 'Bekor qilingan')], default=1, verbose_name='Holat'),
        ),
    ]
