# Generated by Django 4.1.3 on 2022-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_sponsormodel_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='budget',
            field=models.PositiveIntegerField(),
        ),
    ]
