# Generated by Django 4.1.3 on 2022-11-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_sponsormodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='phone_number',
            field=models.CharField(default=0, max_length=9, verbose_name='telefon raqam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='person',
            field=models.BooleanField(choices=[(0, 'Yuridik'), (1, 'Jismoniy')], verbose_name='Shaxs turi'),
        ),
        migrations.AlterField(
            model_name='studentbudgetmodel',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.sponsormodel', verbose_name='Homiy'),
        ),
        migrations.AlterField(
            model_name='studentbudgetmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.studentmodel', verbose_name='Talaba'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.universitymodel', verbose_name='Institut'),
        ),
    ]
